### ISSUE TITLE
Add PR Template

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [MrKrishnaAgarwal/Git-CheatSheet#15]

**Comment by Gurnav224** [comment]
I want to work on the issue . could please assign it to me

![Screenshot from 2023-10-01 12-41-24](https://github.com/MrKrishnaAgarwal/Git-CheatSheet/assets/72142482/da11f792-a452-47cf-8e8c-f60be94405ba)

**Comment by MrKrishnaAgarwal** [comment]
Absolutely!
I’ve assigned it to you.

**Comment by MrKrishnaAgarwal** [comment]
#20 Resolved
