### ISSUE TITLE
Adding more resources to the cheatsheet

### ISSUE THREAD

**Issue by arefathi** [MrKrishnaAgarwal/Git-CheatSheet#4]
Hello @MrKrishnaAgarwal 

Git is such an amazing tool, you are right to have a cheatsheet such as this. This year I decided to hop on to some non-code contributions in October. 

I see that your repo is participating in Hacktoberfest 2022, I would like to add some more commands to the cheatsheet and some other resources regarding Git. Let me know if that's okay. 

Thanks.

**Comment by MrKrishnaAgarwal** [comment]
Yes, go ahead

**Comment by arefathi** [comment]
I have submitted a PR with more commands and a resources section. I hope it is to your satisfaction. 
Ping me if there are any issues. I would be happy to contribute more to the repo as I come across other resources.

Thanks, @MrKrishnaAgarwal and Appreciate it!

**Comment by MrKrishnaAgarwal** [comment]
Thanks a lot 💯
Awesome work man 👌
